version: "3.8"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB = ${DB_NAME}
      - POSTGRES_USER = ${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD = ${POSTGRES_PASSWORD}
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  postgres_volume
