version: "3.8"

services:
  api:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  postgres_volume:
